// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0FxWR5iO5xzBoaXAsuE1fRC-kzC3ohnU',
    appId: '1:593319316684:web:98780a56503ee4ef668669',
    messagingSenderId: '593319316684',
    projectId: 'main-7b198',
    authDomain: 'main-7b198.firebaseapp.com',
    storageBucket: 'main-7b198.firebasestorage.app',
    measurementId: 'G-NPPBJQ5FEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-r9CVQ0LsIdQoWDDpOhJR-V3dgYRo9A',
    appId: '1:593319316684:android:233fd2d451918b6d668669',
    messagingSenderId: '593319316684',
    projectId: 'main-7b198',
    storageBucket: 'main-7b198.firebasestorage.app',
  );
}
